### ISSUE TITLE
tag <i> nie może być elementem bezpośrednio zagnieżdżonym w <ul>

### ISSUE THREAD

**Issue by 84lukaszkaminski** [infoshareacademy/JFDZW2-Django#10]
https://github.com/infoshareacademy/JFDZW2-Django/blob/52598a98a768f765aa96e41339756ec1f0f3926e/index.html#L44

trzeba to zagnieździć w `<li></li>`

**Comment by kmolb** [comment]
poprawione
 <li i class="fas fa-map-marked-alt"></li>
