### ISSUE TITLE
zmienne zamiast wartości na sztywno

### ISSUE THREAD

**Issue by MikeSniegovski** [infoshareacademy/JFDZW2-Django#41]
@AngryKitten91 
https://github.com/infoshareacademy/JFDZW2-Django/blob/cb49a423ccc5e5cabae46b3bed6e9c3b96fe1b36/js/interactions.js#L18

Z tego co rozumiem to jest to warunek żeby gracz nie mógł przesunąć się poza planszę.
Bezpieczniej będzie zamiast wartości na sztywno użyć game.boardHeight

**Comment by AngryKitten91** [comment]
Dzięki za uwagę, poprawione w nowym pull request'cie :)
